name: Pull Request Checks

on:
    pull_request:
        branches:
            - main

jobs:
    does-code-build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup .NET 8.x
              uses: actions/setup-dotnet@v3
              with:
                # Semantic version range syntax or exact version of a dotnet version
                dotnet-version: '8.x'

            - name: Build WeatherForecastService with dotnet CLI
              run: |
                cd WeatherForecastService
                dotnet restore
                dotnet publish -c Release -o out
                
            - name: Build WeatherForecastService Docker image
              run: |
                docker build -t metrics-weather-service:latest WeatherForecastService

            - name: Build SimulatedClients Docker image
              run: |
                docker build -t metrics-weather-client:latest SimulatedClients
